void CheckAmorcer();
void CheckTester();
int CheckTestPersonnage(t_personnage perso);
int CheckTestEtage(t_carte pos);
int CheckMonstre(int x,int y, t_carte carte);
int CheckMur(int x,int y, t_carte carte);
int CheckMonstreVie(int idMob,t_carte carte);
int CheckChemin(int x,int y, t_carte carte);
int CheckUpNiveau(t_personnage player);
int CheckSalle(int x,int y, t_carte carte);
int CheckEscalier(int x, int y, t_carte carte);
